# Generated by Django 5.1.1 on 2024-12-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_alter_proyecto_descripcion_alter_proyecto_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
